# Generated by Django 2.2.17 on 2021-07-25 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0002_auto_20210725_1359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='area',
            name='parent',
        ),
        migrations.AddField(
            model_name='area',
            name='parent_id',
            field=models.CharField(default='', max_length=20, verbose_name='id'),
        ),
    ]
