# Generated by Django 2.2.17 on 2021-07-25 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0004_auto_20210725_1415'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='名称')),
            ],
            options={
                'verbose_name': '民族',
                'verbose_name_plural': '民族',
                'db_table': 'tb_nation',
            },
        ),
    ]
