# Generated by Django 2.2.17 on 2021-07-25 07:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.CharField(max_length=24, primary_key=True, serialize=False, verbose_name='id')),
                ('action', models.CharField(max_length=32, verbose_name='操作')),
                ('desc', models.CharField(max_length=255, verbose_name='操作详情')),
                ('action_time', models.BigIntegerField(verbose_name='发生时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='日志创建时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='UserId')),
            ],
            options={
                'verbose_name': '日志记录',
                'verbose_name_plural': '日志记录',
                'db_table': 't_logs',
                'ordering': ('id',),
            },
        ),
    ]
